#!/usr/bin/env python3
"""
Regression Tests for Policy Gate PII Sanitization

Auto-generated by AI Investigator after identifying a regex bug
in _sanitize_name_in_text() that failed to catch inline name formats.

These tests will FAIL until the bug is fixed.
"""

import unittest
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from policy_gate import sanitize, _sanitize_name_in_text


class TestPolicyGateRegression(unittest.TestCase):
    """Regression tests for the PII sanitization bug."""

    def test_redacts_patient_name_prefix_format(self):
        """Test that 'Patient Name: X' format is redacted."""
        text = "Patient Name: John Smith, DOB 03/15/1978, Diagnosis: Hypertension"
        result, _ = sanitize(text)

        self.assertNotIn("John Smith", result,
            "Name should be redacted in 'Patient Name:' format")

    def test_redacts_patient_name_inline_format(self):
        """Test that 'Patient X, DOB' format is redacted.

        THIS TEST WILL FAIL until the regex bug is fixed!
        The current regex only matches 'Patient Name:' prefix.
        """
        text = "Patient John Smith, DOB 03/15/1978, Record ID: 2847"
        result, _ = sanitize(text)

        self.assertNotIn("John Smith", result,
            "Name should be redacted in 'Patient <Name>, DOB' format")

    def test_redacts_dob(self):
        """Test that DOB is redacted in both formats."""
        text = "Patient John Smith, DOB 03/15/1978, Record ID: 2847"
        result, _ = sanitize(text)

        self.assertNotIn("03/15/1978", result,
            "DOB should be redacted")


def run_tests_with_status():
    """Run tests and return pass/fail status for each."""
    loader = unittest.TestLoader()
    suite = loader.loadTestsFromTestCase(TestPolicyGateRegression)

    results = []
    for test in suite:
        test_result = unittest.TestResult()
        test.run(test_result)

        test_name = str(test).split()[0]
        if test_result.wasSuccessful():
            results.append((test_name, True, None))
        else:
            error = test_result.failures[0][1] if test_result.failures else "Unknown error"
            results.append((test_name, False, error))

    return results


if __name__ == "__main__":
    print("Running Policy Gate Regression Tests...")
    print()

    results = run_tests_with_status()

    for name, passed, error in results:
        status = "✓ PASSED" if passed else "✗ FAILED"
        print(f"  {status}: {name}")
        if error and not passed:
            # Extract just the assertion message
            lines = error.strip().split("\n")
            for line in lines:
                if "AssertionError" in line or "should be" in line.lower():
                    print(f"           {line.strip()}")

    print()

    passed_count = sum(1 for _, p, _ in results if p)
    total = len(results)
    print(f"Results: {passed_count}/{total} tests passed")
