#!/usr/bin/env python3
"""
Regression Test: PII Gate - Patient Name/DOB Format

Generated by Retrace Leak Investigation
This test ensures the policy gate properly sanitizes the vulnerable format.

Root Cause: policy_gate.py:_sanitize_name_in_text() only checks for
'Patient Name:' prefix, missing 'Patient [Name], DOB [Date]' format.
"""

import re
import sys
import os

# Add eval_pipeline to path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..', 'eval_pipeline'))

from policy_gate import policy_gate


class TestPIIGateRegression:
    """Regression tests for PII gate vulnerabilities."""
    
    def test_patient_dob_format_sanitization(self):
        """
        Test that policy gate sanitizes 'Patient [Name], DOB [Date]' format.
        
        This format was missed by the buggy regex which only matched
        'Patient Name: [Name]' format.
        """
        # The vulnerable payload that caused the leak
        test_payload = {
            "tool": "lookup_customer",
            "customer_id": "C-1007",
            "payload": {
                "record_id": 2847,
                "patient_id": "P-447281",
                "name": "John Smith",
                "notes": "Patient John Smith, DOB 03/15/1978, diagnosed with hypertension.",
                "source_file": "datasets/pii_export.json"
            }
        }
        
        # Run through policy gate
        redacted, decision = policy_gate(test_payload)
        
        # Get the redacted notes
        redacted_notes = redacted.get("payload", {}).get("notes", "")
        
        # Assert: Name should not appear in redacted notes
        assert "John Smith" not in redacted_notes, \
            f"Name 'John Smith' should be redacted from notes. Got: {redacted_notes}"
        
        # Assert: DOB should not appear in redacted notes
        dob_pattern = r"\d{2}/\d{2}/\d{4}"
        assert not re.search(dob_pattern, redacted_notes), \
            f"DOB pattern should be redacted from notes. Got: {redacted_notes}"
        
        print("✓ Test passed: PII properly redacted from vulnerable format")
    
    def test_patient_name_prefix_format(self):
        """
        Test that the existing 'Patient Name:' format still works.
        """
        test_payload = {
            "tool": "lookup_customer",
            "customer_id": "C-1001",
            "payload": {
                "notes": "Patient Name: Linda Martinez. Scheduled for screening."
            }
        }
        
        redacted, decision = policy_gate(test_payload)
        redacted_notes = redacted.get("payload", {}).get("notes", "")
        
        # The 'Patient Name:' format should be redacted
        assert "Linda Martinez" not in redacted_notes, \
            f"Name should be redacted. Got: {redacted_notes}"
        
        print("✓ Test passed: 'Patient Name:' format properly redacted")
    
    def test_multiple_pii_formats(self):
        """
        Test that multiple PII formats in the same text are all redacted.
        """
        test_payload = {
            "tool": "lookup_customer",
            "customer_id": "TEST",
            "payload": {
                "notes": "Patient John Doe, DOB 01/01/1980. Patient Name: Jane Doe. ID: P-123456"
            }
        }
        
        redacted, decision = policy_gate(test_payload)
        redacted_notes = redacted.get("payload", {}).get("notes", "")
        
        # All names should be redacted
        assert "John Doe" not in redacted_notes, "John Doe should be redacted"
        assert "Jane Doe" not in redacted_notes, "Jane Doe should be redacted"
        
        # DOB should be redacted
        assert "01/01/1980" not in redacted_notes, "DOB should be redacted"
        
        # Patient ID should be redacted
        assert "P-123456" not in redacted_notes, "Patient ID should be redacted"
        
        print("✓ Test passed: Multiple PII formats all redacted")


def run_tests():
    """Run all regression tests."""
    print("=" * 60)
    print("Running PII Gate Regression Tests")
    print("=" * 60)
    print()
    
    test_class = TestPIIGateRegression()
    
    tests = [
        ("Patient DOB Format", test_class.test_patient_dob_format_sanitization),
        ("Patient Name Prefix Format", test_class.test_patient_name_prefix_format),
        ("Multiple PII Formats", test_class.test_multiple_pii_formats),
    ]
    
    passed = 0
    failed = 0
    
    for test_name, test_fn in tests:
        print(f"Running: {test_name}...")
        try:
            test_fn()
            passed += 1
        except AssertionError as e:
            print(f"   ❌ FAILED: {e}")
            failed += 1
        except Exception as e:
            print(f"   ❌ ERROR: {e}")
            failed += 1
    
    print()
    print("=" * 60)
    print(f"Results: {passed} passed, {failed} failed")
    print("=" * 60)
    
    return failed == 0


if __name__ == "__main__":
    success = run_tests()
    sys.exit(0 if success else 1)
